version: "2"
services:
  app:
    container_name:supply-chain-story
    image: deakinlaunchpad/supplychain-dev
    restart: always

    command: bash -c "npm start"
    ports:
<<<<<<< HEAD
      - "4008:4008"
=======
      - "3014:3014"
>>>>>>> e8270a5539aac5421cdb30d4e34b60cef1fe340d
    
      