version: "2"
services:
  app:
    container_name:supply-chain-story
    image: deakinlaunchpad/supplychain-dev
    restart: always

    command: bash -c "npm start"
    ports:
      - "4008:4008"
    
      